SELECT
    PERS.PERSNBR "Member",
    AddrText.CivicAddr "Address",
    ADDR.CITYNAME "City",
    ADDR.CTRYSUBDIVCD "Province",
    ADDR.CTRYMAILCD "Postal Code"
FROM PERS
LEFT OUTER JOIN
    (SELECT
        PERSNBR,
        ADDRUSECD,
        ADDRNBR
    FROM PERSADDRUSE
    WHERE ADDRUSECD = 'PRI') PriAddr
    ON PERS.PERSNBR = PriAddr.PERSNBR
LEFT OUTER JOIN
    (SELECT
        ADDRLINE.ADDRNBR,
        LISTAGG(ADDRLINE.TEXT, ' ') WITHIN GROUP (ORDER BY ADDRLINE.LINENBR) AS CivicAddr
    FROM ADDRLINE
    GROUP BY ADDRLINE.ADDRNBR) AddrText
    ON PriAddr.ADDRNBR = AddrText.ADDRNBR
LEFT OUTER JOIN ADDR
    ON PriAddr.ADDRNBR = ADDR.ADDRNBR
WHERE PERS.DATEDEATH IS NULL
